### ISSUE TITLE
Styles not working ! Please help

### ISSUE THREAD

**Issue by saif-o99** [hivivo/ngx-json-viewer#104]
![image](https://user-images.githubusercontent.com/52207667/176490448-70edcde5-c3ba-4a36-b1d8-cb0bb4aa4526.png)

no indentation shown, no arrows , the text colors i added them so its not using the default .. whats wrong?

**Comment by saif-o99** [comment]
@hivivo

**Comment by hivivo** [comment]
This does not look like the ngx-json-viewer component. Can you share the
snippets for the usage?

**Comment by saif-o99** [comment]
i added the custom styles because there weren't any ... it solved the problem for the text color but not for the arrows and the indentations

**Comment by saif-o99** [comment]
i fixed it by copying your default styles into my component styles file :)
