### ISSUE TITLE
When you expand it shouldn't expand all 

### ISSUE THREAD

**Issue by snowyaaron1** [hivivo/ngx-json-viewer#13]
So a performance issue I have seen with this repo is that when you use 

`[expanded]="false"`

When you click on the arrow it expands every child array or object and on large JSON objects this brings the browser down to a crawl and you can barely scroll. I would think the intended action would be you would want to open each level of the JSON object with the corresponding arrow.

https://stackblitz.com/edit/ngx-json-viewer?file=app%2Fapp.component.html

You can see when in the example above when you expand one of the objects, that it opens all children. If this is the intention then I understand, however In large JSON objects it will crash the browser(not shown in above demo

**Comment by hivivo** [comment]
Thanks for reporting @snowyaaron1 ! I'll look into this issue soon.

**Comment by benkrig** [comment]
@hivivo @snowyaaron1,

Ran into this issue as well for large JSON Objects. 

I've created pull request https://github.com/hivivo/ngx-json-viewer/pull/15 to fix this.

**Comment by hivivo** [comment]
Thanks @benkrig for the fix!
