### ISSUE TITLE
Support for Angular 7

### ISSUE THREAD

**Issue by pabloFuente** [hivivo/ngx-json-viewer#17]
Hi!

Right now when using Angular version 7.0.0-rc.0 this warn appears when installing latest
`"ngx-json-viewer": "2.3.1"`

```
npm WARN ngx-json-viewer@2.3.1 requires a peer of @angular/core@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-json-viewer@2.3.1 requires a peer of @angular/common@>=5.0.0 but none is installed. You must install peer dependencies yourself.
```

This component probably works fine despite the WARN message, but it would be nice not having it when running npm.

**Comment by hivivo** [comment]
Hi @pabloFuente,

I tried Angular `7.0.1` and there is no warning like above. Can you please verify?

Thanks!
