### ISSUE TITLE
Not working with Angular 5.2

### ISSUE THREAD

**Issue by steinsag** [hivivo/ngx-json-viewer#2]
I followed your instructions to install the plugin. I generated my Angular project just a few days ago with latest Angular CLI version. After adding your module via npm install, I get the following error when compiling my project (ng serve):

> ERROR in ./node_modules/ngx-json-viewer/index.ts
> Module build failed: Error: /home/user/angular/node_modules/ngx-json-viewer/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (/home/user/angular/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
>     at plugin.done.then (/home/user/angular/node_modules/@ngtools/webpack/src/loader.js:467:39)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>  @ ./src/app/app.module.ts 13:24-50
>  @ ./src/main.ts
>  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

Now, I copied your source code into my project manually like a component implemented by myself and it works. So they probably just changed something how modules must be packaged.

**Comment by hivivo** [comment]
thanks for reporting! I'll investigate and let you know soon.
