### ISSUE TITLE
how to add horizontal scroll if width increases further in this component while compacting json?

### ISSUE THREAD

**Issue by shekharramola** [hivivo/ngx-json-viewer#3]
Hi, I am using your package to view the JSON data which is having so long width if I make it compact.
If I view using json pipe
{{bureauJSON|json}}
 then, it is adding horizontal scroll to view the data

However, if I use  <app-ngx-json-viewer [json]="bureauJSON"></app-ngx-json-viewer> then content only come till the screen size, other content will be lost.

**Comment by hivivo** [comment]
thanks for reporting. I'll fix it.
