### ISSUE TITLE
Library not working properly with Angular 9

### ISSUE THREAD

**Issue by MoEffat** [hivivo/ngx-json-viewer#31]
Hello,
The Json is whether expanded or not. I cannot toggle between the 2 states, When I click at the Json parent node nothing happens.
Thanks

**Comment by connormulcahey** [comment]
For clarity - you are saying the expand/collapse triangle handles aren't doing anything? 

If so, I am observing this as well.

**Comment by jonathan-chin** [comment]
I'm experiencing this as well. however, I bound a function to the click event:

```
        <ngx-json-viewer
          (click)='triggerChangeDetection()'
          [json]='result'>
        </ngx-json-viewer>
```

and just called `this.changeDetectorRef.detectChanges()` in the bound function. it seems to work for me.
