### ISSUE TITLE
Can't bind to 'json' since it isn't a known property of 'ngx-json-viewer'

### ISSUE THREAD

**Issue by RoraxHan** [hivivo/ngx-json-viewer#7]
I'm using angular 4 and I added this module to my sub module called SettingsModule,
but I'v got like this error in browser console.
Maybe project doesn't know about ngx-json-viewer component

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'json' since it isn't a known property of 'ngx-json-viewer'.
1. If 'ngx-json-viewer' is an Angular component and it has 'json' input, then verify that it is part of this module.
2. If 'ngx-json-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("gx-json-viewer [json]="deviceHealth.iikoGroups"></ngx-json-viewer> -->
            <ngx-json-viewer [ERROR ->][json]="test"></ngx-json-viewer>
            
        </div>
"): ng:///SettingsModule/SettingsComponent.html@271:29
'ngx-json-viewer' is not a known element:
1. If 'ngx-json-viewer' is an Angular component, then verify that it is part of this module.
2. If 'ngx-json-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("          <!-- <ngx-json-viewer [json]="deviceHealth.iikoGroups"></ngx-json-viewer> -->
            [ERROR ->]<ngx-json-viewer [json]="test"></ngx-json-viewer>
            
        </div>
"): ng:///SettingsModule/SettingsComponent.html@271:12
Error: Template parse errors:
Can't bind to 'json' since it isn't a known property of 'ngx-json-viewer'.
1. If 'ngx-json-viewer' is an Angular component and it has 'json' input, then verify that it is part of this module.
2. If 'ngx-json-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("gx-json-viewer [json]="deviceHealth.iikoGroups"></ngx-json-viewer> -->
            <ngx-json-viewer [ERROR ->][json]="test"></ngx-json-viewer>
            
```

I can see message like below in vs code lint.
```
[Angular]
'ngx-json-viewer' is not a known element:
1. If 'ngx-json-viewer' is an Angular component, then verify that it is part of this module.
2. If 'ngx-json-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
Could you help me how to use this component exactly?

**Comment by hivivo** [comment]
Are you saying you are using the source code as part of your project instead of npm installing? Can I see your SettingsModule file?

**Comment by RoraxHan** [comment]
thanks for replying.
of course, I've installed this using npm.
instead of app.module.ts, I imported this in other module of my project.

```
// some code
import { NgxJsonViewerModule } from 'ngx-json-viewer';

export const routes = [
  { path: '', component: SettingsComponent, pathMatch: 'full' }
]

@NgModule({
  imports: [
    // some module
    NgxJsonViewerModule,

    ToastrModule.forRoot(),
    RouterModule.forChild(routes)
  ],
  declarations: [SettingsComponent]
})
export class SettingsModule { }

```

**Comment by hivivo** [comment]
can you try to install latest version instead of 1.0?
please try  2.2.0

**Comment by RoraxHan** [comment]
I'm using angular 4.
So I followed this from your doc.
```
# For Angular 5:
npm install ngx-json-viewer

# For Angular 2/4:
npm install ngx-json-viewer@1
```

can I try 2.2.0 with angular 4?
and if that's ok, then I need to try with this?
`npm install ngx-json-viewer@2.2.0`

**Comment by hivivo** [comment]
yes. please try it. I tried a simple Angular 4 project, and it seems good. If you are successful, I'll update the doc accordingly.

**Comment by RoraxHan** [comment]
yes. that works fine. 
Probably you need to update your document to help others.
Thanks for making good library and helping me.
I want to give more star. 👍

**Comment by hivivo** [comment]
Thank you for pointing the issue out, Shine. I'll update the doc later :)

**Comment by RoraxHan** [comment]
welcome~
last question!!
Can I change some style easily?

**Comment by hivivo** [comment]
sorry not now. probably it's a future goal for me.

**Comment by hivivo** [comment]
for the collapse, you can try [expanded]=false

**Comment by RoraxHan** [comment]
Got it! I hope this library will be amazing time goes by.
Collapsing all node by default is not supported now?

If you add some method to customize easily, then this will be more good.
(I'll try that by inspecting element.)
Thanks for your time!

**Comment by kowsalyasivasamy** [comment]
Hi, I am using angular 6, me also getting a same error. already tried the above mentioned solutions but still not fixed.

**Comment by ohabash** [comment]
doesnt work in ng8?

**Comment by hivivo** [comment]
> doesnt work in ng8?

it works in Angular 8 as in the example here: https://stackblitz.com/edit/angular-8-getting-started-yyr7ce?file=src/app/app.component.html

If it's not working for you, please make a new ticket with your example.
