### ISSUE TITLE
change the by default opening of json structure to close

### ISSUE THREAD

**Issue by shekharramola** [hivivo/ngx-json-viewer#9]
Hi, I am currently using your component to view json and it is very nice however I have multiple json to display. So what I need to do is to change the by default opening of json structure to by default closed. Any idea how can I achieve that?

**Comment by hivivo** [comment]
[expanded]=false

**Comment by hivivo** [comment]
check out the bottom of README please. Let me know if that meets your requirement.

**Comment by shekharramola** [comment]
Hey, it is working perfectly. I just need to add `::ng-deep .ngx-json-viewer {
    overflow: auto !important;
}`

thanks :)
